server:
  port: 8090
  
swagger:
  paths: /api.*
  apiInfoTitle: @project.artifactId@
  apiInfoDescription: @project.name@ Documentation
  apiInfoContactEmail: swagger.project.contact
  apiInfoContactName: toto@gmail.com
  apiInfoContactURL: toto.fr
  apiInfoVersion: @pom.version@
  apiInfoLicense: license
  apiInfoLicenseUrl: http://easyms.fr/LICENSE-0.0.1.html

spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
    platform: h2

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  # enable H2 web console and set url for web console
  # http://localhost:8090/console
  h2:
    console:
      enabled: true
      path: /console

logging:
  level:
    org:
      hibernate:
        type: trace


